name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Bogdanp/setup-racket@v1.9
        with:
          architecture: x64
          distribution: full
          variant: CS
          version: 8.7
      - run: raco pkg install
      - run: raco test test
